# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: wimmol
      POSTGRES_PASSWORD: fe67!klJ_Dwdwd6k_31Wdw_DQd)wq3
      POSTGRES_DB: buy-crypto-db

  bot:
    image: bot
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
